### ISSUE TITLE
[BUG] 持续性崩溃

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1088]
**bug现象**
运行了服务器端一段时间, 今天登陆服务器看到一大堆的core文件, 看文件日期, 差不多每隔几个小时生成一次.
使用gdb查看的堆栈如下
```
#0  0x00007f819069553f in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f8190697098 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f81903c5ff8 in __GI___backtrace (array=<optimized out>, size=<optimized out>) at ../sysdeps/x86_64/backtrace.c:111
#3  0x000055dee3c7abe4 in sig_crash(int) ()
#4  <signal handler called>
#5  0x0000000000000001 in ?? ()
#6  0x000055dee3f1a67e in bio_read_intern ()
#7  0x000055dee3f1ac53 in BIO_read ()
#8  0x000055dee3ee4f8d in toolkit::SSL_Box::flushWriteBio() ()
#9  0x000055dee3ee5570 in toolkit::SSL_Box::flush() ()
#10 0x000055dee3ee5a03 in toolkit::SSL_Box::onRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#11 0x000055dee3eb7bf0 in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::TcpClient::onSockConnect(toolkit::SockException const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#3}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*&&, int&&) ()
#12 0x000055dee3eaf1c8 in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#13 0x000055dee3eb1111 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#14 0x000055dee3ecd392 in toolkit::EventPoller::runLoop(bool, bool) ()
#15 0x00007f8190cf96df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007f8190fcc6db in start_thread (arg=0x7f818abff700) at pthread_create.c:463
#17 0x00007f81903b671f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**bug产生时的使用场景**
拉了几个https的测试流, 因为之前在本地时候就有出现崩溃记录, 但是一直没有办法复现.
所以放到服务器上, 随便找了几个https的hls流长时间拉取, 看看是否会崩溃

**bug是否可以复现，怎么复现**
不清楚是哪个测试流导致的, 测试流来源于网络上找到的hls的直播流.

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
ubuntu 18.04 x64

**Comment by xia-chu** [comment]
这个太诡异了 我会测试下看看

**Comment by xia-chu** [comment]
不好意思 我用valgrind和asan测试 zlmediakit的hls(over https)播放器和服务器,都不存在内存越界的问题

**Comment by xia-chu** [comment]
而且我用项目商用了zlm的https功能 也遇到越界崩溃的问题

**Comment by alexliyu7352** [comment]
会不会是openssl版本的问题?我采用了静态编译openssl的原因?

**Comment by xia-chu** [comment]
> 会不会是openssl版本的问题?我采用了静态编译openssl的原因?

建议你用valgrind或asan调试看看。
cmake -DENABLE_ASAN可以开启asan编译

**Comment by alexliyu7352** [comment]
#0  0x00007f995400753f in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007f9954009098 in _Unwind_Backtrace () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007f9953d37ff8 in __GI___backtrace (array=<optimized out>, size=<optimized out>) at ../sysdeps/x86_64/backtrace.c:111
#3  0x000055ed7c381dc4 in sig_crash(int) ()
#4  <signal handler called>
#5  0x0000000000000001 in ?? ()
#6  0x00007f9954c01e2e in ?? () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#7  0x00007f9954c02403 in BIO_read () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#8  0x000055ed7c625ded in toolkit::SSL_Box::flushWriteBio() ()
#9  0x000055ed7c6263d0 in toolkit::SSL_Box::flush() ()
#10 0x000055ed7c626863 in toolkit::SSL_Box::onRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#11 0x000055ed7c5f76e0 in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::TcpClient::onSockConnect(toolkit::SockException const&)::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#3}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*&&, int&&) ()
#12 0x000055ed7c5eec98 in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#13 0x000055ed7c5f0be1 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#14 0x000055ed7c60eb23 in toolkit::EventPoller::runLoop(bool, bool) ()
#15 0x00007f995466b6df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007f995493e6db in start_thread (arg=0x7f994a3ff700) at pthread_create.c:463
#17 0x00007f9953d2871f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95


仍旧是这样
