### ISSUE TITLE
[BUG]: 媒体服务器运行一段时间崩溃

### ISSUE THREAD

**Issue by panjingang1980** [ZLMediaKit/ZLMediaKit#1681]
### 现象描述
同时接入GB28181和RTSP视频流后，运行十个后小时后，生成core文件

```bash
## crash date:2022-06-01 23:30:50
## exe:       MediaServer
## signal:    11
## stack:     
[0]: ./MediaServer() [0xbcbd58]
sig_crash(int)
System.cpp:?

[1]: /lib64/libc.so.6(+0x36400) [0x7f01582f6400]
??
??:0

[2]: ./MediaServer(_ZN8mediakit9RtpPacket9getHeaderEv+0x10) [0xdf7232]
mediakit::RtpPacket::getHeader()
??:?

[3]: ./MediaServer(_ZN8mediakit14GB28181Process11onRtpSortedESt10shared_ptrINS_9RtpPacketEE+0x24) [0xee4ee2]
mediakit::GB28181Process::onRtpSorted(std::shared_ptr<mediakit::RtpPacket>)
??:?

[4]: ./MediaServer() [0xee513b]
mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long)::{lambda(std::shared_ptr<mediakit::RtpPacket>)#5}::operator()(std::shared_ptr<mediakit::RtpPacket>) const
GB28181Process.cpp:?

[5]: ./MediaServer() [0xeea7b0]
std::_Function_handler<void (std::shared_ptr<mediakit::RtpPacket>), mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long)::{lambda(std::shared_ptr<mediakit::RtpPacket>)#5}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mediakit::RtpPacket>)
GB28181Process.cpp:?

[6]: ./MediaServer(_ZNKSt8functionIFvSt10shared_ptrIN8mediakit9RtpPacketEEEEclES3_+0x5c) [0xf076de]
std::function<void (std::shared_ptr<mediakit::RtpPacket>)>::operator()(std::shared_ptr<mediakit::RtpPacket>) const
??:?

[7]: ./MediaServer(_ZN8mediakit11RtpTrackImp11onRtpSortedESt10shared_ptrINS_9RtpPacketEE+0x5f) [0xf06123]
mediakit::RtpTrackImp::onRtpSorted(std::shared_ptr<mediakit::RtpPacket>)
??:?

[8]: ./MediaServer() [0xf05471]
mediakit::RtpTrack::RtpTrack()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const
RtpReceiver.cpp:?

[9]: ./MediaServer() [0xf063df]
std::_Function_handler<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&), mediakit::RtpTrack::RtpTrack()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}>::_M_invoke(std::_Any_data const&, unsigned short, std::shared_ptr<mediakit::RtpPacket>&)
RtpReceiver.cpp:?

[10]: ./MediaServer(_ZNKSt8functionIFvtRSt10shared_ptrIN8mediakit9RtpPacketEEEEclEtS4_+0x65) [0xf084f1]
std::function<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&)>::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const
??:?

[11]: ./MediaServer(_ZN8mediakit12PacketSortorISt10shared_ptrINS_9RtpPacketEEtLm1024ELm32EE9popPacketEv+0x130) [0xf07e22]
mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::popPacket()
??:?

[12]: ./MediaServer(_ZN8mediakit12PacketSortorISt10shared_ptrINS_9RtpPacketEEtLm1024ELm32EE12tryPopPacketEv+0xca) [0xf07956]
mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::tryPopPacket()
??:?

[13]: ./MediaServer(_ZN8mediakit12PacketSortorISt10shared_ptrINS_9RtpPacketEEtLm1024ELm32EE10sortPacketEtS3_+0xb9) [0xf07571]
mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::sortPacket(unsigned short, std::shared_ptr<mediakit::RtpPacket>)
??:?

[14]: ./MediaServer(_ZN8mediakit8RtpTrack8inputRtpENS_9TrackTypeEiPhm+0x754) [0xf05ea0]
mediakit::RtpTrack::inputRtp(mediakit::TrackType, int, unsigned char*, unsigned long)
??:?

[15]: ./MediaServer(_ZN8mediakit14RtpReceiverImp8inputRtpENS_9TrackTypeEPhm+0x43) [0xeeb6e5]
mediakit::RtpReceiverImp::inputRtp(mediakit::TrackType, unsigned char*, unsigned long)
??:?

[16]: ./MediaServer(_ZN8mediakit14GB28181Process8inputRtpEbPKcm+0xb22) [0xee5e3c]
mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long)
??:?

[17]: ./MediaServer(_ZN8mediakit10RtpProcess8inputRtpEbRKSt10shared_ptrIN7toolkit6SocketEEPKcmPK8sockaddrPj+0x55d) [0xdcdedd]
mediakit::RtpProcess::inputRtp(bool, std::shared_ptr<toolkit::Socket> const&, char const*, unsigned long, sockaddr const*, unsigned int*)
??:?

[18]: ./MediaServer(_ZN8mediakit10RtpSession11onRtpPacketEPKcm+0x417) [0xdf0421]
mediakit::RtpSession::onRtpPacket(char const*, unsigned long)
??:?

[19]: ./MediaServer(_ZN8mediakit10RtpSession6onRecvERKSt10shared_ptrIN7toolkit6BufferEE+0x7d) [0xdefa71]
mediakit::RtpSession::onRecv(std::shared_ptr<toolkit::Buffer> const&)
??:?

[20]: ./MediaServer() [0xf5d08c]
toolkit::UdpServer::createSession(unsigned long const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const
UdpServer.cpp:?

[21]: ./MediaServer() [0xf5f156]
std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::UdpServer::createSession(unsigned long const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)
UdpServer.cpp:?

[22]: ./MediaServer(_ZNKSt8functionIFvRKSt10shared_ptrIN7toolkit6BufferEEP8sockaddriEEclES5_S7_i+0x75) [0xf489cb]
std::function<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)>::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const
??:?

[23]: ./MediaServer(_ZN7toolkit6Socket6onReadERKSt10shared_ptrINS_6SockFDEEb+0x2d6) [0xf3ec90]
toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool)
??:?

[24]: ./MediaServer() [0xf3e652]
toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}::operator()(int) const
Socket.cpp:?

[25]: ./MediaServer() [0xf43859]
std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int)
Socket.cpp:?

[26]: ./MediaServer(_ZNKSt8functionIFviEEclEi+0x46) [0xd331e4]
std::function<void (int)>::operator()(int) const
??:?

[27]: ./MediaServer(_ZN7toolkit11EventPoller7runLoopEbb+0x317) [0xf6df59]
toolkit::EventPoller::runLoop(bool, bool)
??:?

[28]: ./MediaServer(_ZNKSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEclIJbbEvEEvPS1_DpOT_+0x9a) [0xf7c1d8]
void std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const
??:?

[29]: ./MediaServer(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS2_bbEE9_M_invokeIILm0ELm1ELm2EEEEvSt12_Index_tupleIIXspT_EEE+0x7b) [0xf7bfef]
void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>)
??:?

[30]: ./MediaServer(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS2_bbEEclEv+0x1b) [0xf7bd2f]
std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()()
??:?

[31]: ./MediaServer(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS4_bbEEE6_M_runEv+0x1c) [0xf7ba78]
std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run()
??:?

[32]: /lib64/libstdc++.so.6(+0xc8421) [0x7f01595f5421]
??
??:0

[33]: /lib64/libpthread.so.0(+0x7ea5) [0x7f0158badea5]
??
??:0

[34]: /lib64/libc.so.6(clone+0x6d) [0x7f01583be9fd]
??
??:0



-----------------------------------------
GDB core


[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./MediaServer -d'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000df7232 in mediakit::RtpPacket::getHeader() ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-50.el7.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 openssl-libs-1.0.2k-21.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-19.el7_9.x86_64
(gdb) bt
#0  0x0000000000df7232 in mediakit::RtpPacket::getHeader() ()
#1  0x0000000000ee4ee2 in mediakit::GB28181Process::onRtpSorted(std::shared_ptr<mediakit::RtpPacket>) ()
#2  0x0000000000ee513b in mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long)::{lambda(std::shared_ptr<mediakit::RtpPacket>)#5}::operator()(std::shared_ptr<mediakit::RtpPacket>) const ()
#3  0x0000000000eea7b0 in std::_Function_handler<void (std::shared_ptr<mediakit::RtpPacket>), mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long)::{lambda(std::shared_ptr<mediakit::RtpPacket>)#5}>::_M_invoke(std::_Any_data const&, std::shared_ptr<mediakit::RtpPacket>) ()
#4  0x0000000000f076de in std::function<void (std::shared_ptr<mediakit::RtpPacket>)>::operator()(std::shared_ptr<mediakit::RtpPacket>) const ()
#5  0x0000000000f06123 in mediakit::RtpTrackImp::onRtpSorted(std::shared_ptr<mediakit::RtpPacket>) ()
#6  0x0000000000f05471 in mediakit::RtpTrack::RtpTrack()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const ()
#7  0x0000000000f063df in std::_Function_handler<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&), mediakit::RtpTrack::RtpTrack()::{lambda(unsigned short, std::shared_ptr<mediakit::RtpPacket>&)#1}>::_M_invoke(std::_Any_data const&, unsigned short, std::shared_ptr<mediakit::RtpPacket>&) ()
#8  0x0000000000f084f1 in std::function<void (unsigned short, std::shared_ptr<mediakit::RtpPacket>&)>::operator()(unsigned short, std::shared_ptr<mediakit::RtpPacket>&) const ()
#9  0x0000000000f07e22 in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::popPacket() ()
#10 0x0000000000f07956 in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::tryPopPacket() ()
#11 0x0000000000f07571 in mediakit::PacketSortor<std::shared_ptr<mediakit::RtpPacket>, unsigned short, 1024ul, 32ul>::sortPacket(unsigned short, std::shared_ptr<mediakit::RtpPacket>) ()
#12 0x0000000000f05ea0 in mediakit::RtpTrack::inputRtp(mediakit::TrackType, int, unsigned char*, unsigned long) ()
#13 0x0000000000eeb6e5 in mediakit::RtpReceiverImp::inputRtp(mediakit::TrackType, unsigned char*, unsigned long) ()
#14 0x0000000000ee5e3c in mediakit::GB28181Process::inputRtp(bool, char const*, unsigned long) ()
#15 0x0000000000dcdedd in mediakit::RtpProcess::inputRtp(bool, std::shared_ptr<toolkit::Socket> const&, char const*, unsigned long, sockaddr const*, unsigned int*) ()
#16 0x0000000000df0421 in mediakit::RtpSession::onRtpPacket(char const*, unsigned long) ()
#17 0x0000000000defa71 in mediakit::RtpSession::onRecv(std::shared_ptr<toolkit::Buffer> const&) ()
#18 0x0000000000f5d08c in toolkit::UdpServer::createSession(unsigned long const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#19 0x0000000000f5f156 in std::_Function_handler<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int), toolkit::UdpServer::createSession(unsigned long const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) ()
#20 0x0000000000f489cb in std::function<void (std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int)>::operator()(std::shared_ptr<toolkit::Buffer> const&, sockaddr*, int) const ()
#21 0x0000000000f3ec90 in toolkit::Socket::onRead(std::shared_ptr<toolkit::SockFD> const&, bool) ()
#22 0x0000000000f3e652 in toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}::operator()(int) const ()
#23 0x0000000000f43859 in std::_Function_handler<void (int), toolkit::Socket::attachEvent(std::shared_ptr<toolkit::SockFD> const&, bool)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int) ()
#24 0x0000000000d331e4 in std::function<void (int)>::operator()(int) const ()
#25 0x0000000000f6df59 in toolkit::EventPoller::runLoop(bool, bool) ()
#26 0x0000000000f7c1d8 in void std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const ()
#27 0x0000000000f7bfef in void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(---Type <return> to continue, or q <return> to quit---f
std::_Index_tuple<0ul, 1ul, 2ul>) ()
#28 0x0000000000f7bd2f in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()() ()
#29 0x0000000000f7ba78 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run()
    ()
#30 0x00007f01595f5421 in std::execute_native_thread_routine_compat (__p=<optimized out>)

```

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
* **代码提交记录/git commit hash**:

commit 2242577661ee7650fe0bbf0d88d4956d5235c203
Author: ziyue <1213642868@qq.com>
Date:   Fri Aug 27 11:05:26 2021 +0800

* **操作系统及版本**:
Linux version 3.10.0-1127.13.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Tue Jun 23 15:46:38 UTC 2020

* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个代码距今快1年了，期间应该修复很多bug，建议你同步下最新代码。

**Comment by xia-chu** [comment]
这个问题看backtrack看不错端倪 可能是内存越界导致的；我们也发现第三方库有点内存bug
