### ISSUE TITLE
[BUG]: arm64下拉流停止时会崩溃

### ISSUE THREAD

**Issue by momooy** [ZLMediaKit/ZLMediaKit#2160]
### 现象描述
在使用rtsp拉流时，如果断开rtsp流就会导致程序段错误

### 如何复现?
先使用PlayerProxy播放ipc的rtsp流，然后断开ipc，就必现该问题
临时处理办法：将kResetWhenRePlay配置设置为0，不调用strongSelf->_muxer.reset();这一句就不会段错误

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
使用gdb打印堆栈信息如下：
#0  0x00000000004613dc in __gnu_cxx::__exchange_and_add (__mem=0x9, __val=-1)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:49
#1  0x0000000000461468 in __gnu_cxx::__exchange_and_add_dispatch (__mem=0x9,
    __val=-1)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:82
#2  0x0000000000471794 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:151
#3  0x000000000047006c in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fb0305ff8, __in_chrg=<optimized out>)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:684
#4  0x00000000005b4d28 in std::__shared_ptr<mediakit::RtmpMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fb0305ff0,
    __in_chrg=<optimized out>)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1123
#5  0x00000000005b4d48 in std::shared_ptr<mediakit::RtmpMediaSourceMuxer>::~shared_ptr (this=0x7fb0305ff0, __in_chrg=<optimized out>)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include---Type <return> to continue, or q <return> to quit---
/c++/7.3.0/bits/shared_ptr.h:93
#6  0x00000000005b508c in mediakit::MultiMediaSourceMuxer::~MultiMediaSourceMuxer (this=0x7fb0305c80, __in_chrg=<optimized out>)
    at /home/momooy/tmp/tmp.RM91addAju/inc/zlmediakit/Common/MultiMediaSourceMuxer.h:38
#7  0x00000000004717c0 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7fb0305c70)
    at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:154
#8  0x0000000000681248 in std::_Function_handler<void (toolkit::SockException const&), mediakit::PlayerProxy::play(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(toolkit::SockException const&)#2}>::_M_invoke(std::_Any_data const&, toolkit::SockException const&) ()
#9  0x00000000006fa6bc in mediakit::RtspPlayer::onPlayResult_l(toolkit::SockException const&, bool) ()
#10 0x00000000006fbbe0 in std::_Function_handler<bool (), mediakit::RtspPlayer::onPlayResult_l(toolkit::SockException const&, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#11 0x000000000086e260 in std::_Function_handler<unsigned long (), toolkit::Timer::Timer(float, std::function<bool ()> const&, std::shared_ptr<toolkit::EventPoller> const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#12 0x00000000008699c4 in toolkit::EventPoller::flushDelayTask(unsigned long)
    ()
---Type <return> to continue, or q <return> to quit---
#13 0x000000000086a0f4 in toolkit::EventPoller::runLoop(bool, bool) ()
#14 0x0000007fbec287ec in ?? () from /lib64/libstdc++.so.6
#15 0x0000007fbed128f0 in ?? () from /lib64/libpthread.so.0
#16 0x0000007fbe9ec39c in ?? () from /lib64/libc.so.6
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[general]
addMuteAudio=0
check_nvidia_dev=0
continue_push_ms=0
enableVhost=0
enable_audio=0
enable_ffmpeg_log=0
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=mj0Gre2XRCiIlOvu
mergeWriteMS=0
modifyStamp=0
publishToHls=0
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=20000
ts_demand=0
unready_frame_cache=30
wait_add_track_ms=3000
wait_track_ready_ms=5000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
filePath=./www
segDur=2
segKeep=0
segNum=3
segRetain=5

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:b3fd74c,branch:master,build time:Nov 23 2022 10:46:24)</center></body></html>
port=8080
rootPath=./www
sendBufSize=65536
sslport=8081
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
mp4_as_player=0
sampleMS=500

[rtc]
externIP=$LANIP,$WIFIIP
port=8082
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1X,VP9,VP8
rembBitRate=0
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=8083

[rtp]
audioMtuSize=600
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port_range=30000-35000
ps_pt=96
timeoutSec=15
ts_pt=33

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=8084
sslport=8085

[shell]
maxReqSize=1024

; } ---
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: 使用最新版本
* **操作系统及版本**:  Linux 4.19.41
* **硬件信息**: 海思hi3531dv200处理器，64位arm内核
* **其他需要补充的信息**:

**Comment by momooy** [comment]
以下为debug版本抓取的堆栈信息：
#0  0x000000000045874c in __gnu_cxx::__exchange_and_add (__mem=0x9, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:49
#1  0x00000000004587d8 in __gnu_cxx::__exchange_and_add_dispatch (__mem=0x9, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:82
#2  0x0000000000468b04 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:151
#3  0x00000000004673dc in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f2410ea18, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:684
#4  0x00000000005ac098 in std::__shared_ptr<mediakit::RtmpMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f2410ea10, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1123
#5  0x00000000005ac0b8 in std::shared_ptr<mediakit::RtmpMediaSourceMuxer>::~shared_ptr (this=0x7f2410ea10, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h:93
#6  0x00000000005ac3fc in mediakit::MultiMediaSourceMuxer::~MultiMediaSourceMuxer (this=0x7f2410e6a0, __in_chrg=<optimized out>) at /home/momooy/tmp/tmp.RM91addAju/inc/zlmediakit/Common/MultiMediaSourceMuxer.h:38
#7  0x000000000070efd4 in __gnu_cxx::new_allocator<mediakit::MultiMediaSourceMuxer>::destroy<mediakit::MultiMediaSourceMuxer> (this=0x7f2410e6a0, __p=0x7f2410e6a0) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/new_allocator.h:140
#8  0x000000000070ef90 in std::allocator_traits<std::allocator<mediakit::MultiMediaSourceMuxer> >::destroy<mediakit::MultiMediaSourceMuxer> (__a=..., __p=0x7f2410e6a0) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/alloc_traits.h:487
#9  0x000000000070ea1c in std::_Sp_counted_ptr_inplace<mediakit::MultiMediaSourceMuxer, std::allocator<mediakit::MultiMediaSourceMuxer>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7f2410e690) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:535
#10 0x0000000000468b30 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f2410e690) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:154
#11 0x00000000004673dc in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f1670d238, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:684
#12 0x000000000066e6a8 in std::__shared_ptr<mediakit::MultiMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f1670d230, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1123
#13 0x000000000070b420 in std::__shared_ptr<mediakit::MultiMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::reset (this=0x7f255e2d08) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1235
#14 0x000000000070486c in mediakit::PlayerProxy::<lambda(const toolkit::SockException&)>::operator()(const toolkit::SockException &) const (__closure=0x7f257fdec0, err=...) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Player/PlayerProxy.cpp:91
#15 0x0000000000706efc in std::_Function_handler<void(const toolkit::SockException&), mediakit::PlayerProxy::play(const string&)::<lambda(const toolkit::SockException&)> >::_M_invoke(const std::_Any_data &, const toolkit::SockException &) (__functor=..., __args#0=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:316
#16 0x0000000000605b64 in std::function<void (toolkit::SockException const&)>::operator()(toolkit::SockException const&) const (this=0x7f257fe7f0, __args#0=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#17 0x00000000007eb9cc in mediakit::PlayerImp<mediakit::RtspPlayer, mediakit::PlayerBase>::onShutdown (this=0x7f257fe100, ex=...) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Player/PlayerBase.h:212
#18 0x00000000007e1d40 in mediakit::RtspPlayer::onPlayResult_l (this=0x7f257fe100, ex=..., handshake_done=true) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Rtsp/RtspPlayer.cpp:698
#19 0x00000000007e1adc in mediakit::RtspPlayer::<lambda()>::operator()(void) const (__closure=0x7f2410b8c0) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Rtsp/RtspPlayer.cpp:716
#20 0x00000000007e4234 in std::_Function_handler<bool(), mediakit::RtspPlayer::onPlayResult_l(const toolkit::SockException&, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:302
#21 0x00000000009bf2ac in std::function<bool ()>::operator()() const (this=0x7f25638500) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#22 0x00000000009f5470 in toolkit::Timer::<lambda()>::operator()(void) const (__closure=0x7f25638500) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/Timer.cpp:22
#23 0x00000000009f58f4 in std::_Function_handler<long unsigned int(), toolkit::Timer::Timer(float, const std::function<bool()>&, const Ptr&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:302
#24 0x00000000009ec98c in std::function<unsigned long ()>::operator()() const (this=0x7f2410da60) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#25 0x00000000009eafb4 in toolkit::TaskCancelableImp<unsigned long ()>::operator()() const (this=0x7f2410b8f0) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Thread/TaskExecutor.h:111
#26 0x00000000009e72e0 in toolkit::EventPoller::flushDelayTask (this=0x7f255f1300, now_time=23071) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:394
#27 0x00000000009e7578 in toolkit::EventPoller::getMinDelay (this=0x7f255f1300) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:428
#28 0x00000000009e6eb8 in toolkit::EventPoller::runLoop (this=0x7f255f1300, blocked=true, ref_self=true) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:291
#29 0x00000000009ec5d4 in std::__invoke_impl<void, void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__f=@0x7f255f0418: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x9e6ddc <toolkit::EventPoller::runLoop(bool, bool)>, __t=@0x7f255f0410: 0x7f255f1300, __args#0=@0x7f255f0409: true, __args#1=@0x7f255f0408: true) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/invoke.h:73
#30 0x00000000009ead24 in std::__invoke<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__fn=@0x7f255f0418: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x9e6ddc <toolkit::EventPoller::runLoop(bool, bool)>, __args#0=@0x7f255f0410: 0x7f255f1300, __args#1=@0x7f255f0409: true, __args#2=@0x7f255f0408: true) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/invoke.h:95
#31 0x00000000009f4e2c in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::_M_invoke<0ul, 1ul, 2ul, 3ul> (this=0x7f255f0408) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:234
#32 0x00000000009f4c4c in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::operator() (this=0x7f255f0408) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:243
#33 0x00000000009f4a40 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> > >::_M_run (this=0x7f255f0400) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:186
#34 0x0000007fbec287ec in ?? () from target:/lib64/libstdc++.so.6
#35 0x0000007fbed128f0 in ?? () from target:/lib64/libpthread.so.0
#36 0x0000007fbe9ec39c in ?? () from target:/lib64/libc.so.6

**Comment by momooy** [comment]
<details>
<summary>展开查看详细日志(zlm debug版本抓取的堆栈信息)</summary>
<pre>
#0  0x000000000045874c in __gnu_cxx::__exchange_and_add (__mem=0x9, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:49
#1  0x00000000004587d8 in __gnu_cxx::__exchange_and_add_dispatch (__mem=0x9, __val=-1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/atomicity.h:82
#2  0x0000000000468b04 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x1) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:151
#3  0x00000000004673dc in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f2410ea18, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:684
#4  0x00000000005ac098 in std::__shared_ptr<mediakit::RtmpMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f2410ea10, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1123
#5  0x00000000005ac0b8 in std::shared_ptr<mediakit::RtmpMediaSourceMuxer>::~shared_ptr (this=0x7f2410ea10, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr.h:93
#6  0x00000000005ac3fc in mediakit::MultiMediaSourceMuxer::~MultiMediaSourceMuxer (this=0x7f2410e6a0, __in_chrg=<optimized out>) at /home/momooy/tmp/tmp.RM91addAju/inc/zlmediakit/Common/MultiMediaSourceMuxer.h:38
#7  0x000000000070efd4 in __gnu_cxx::new_allocator<mediakit::MultiMediaSourceMuxer>::destroy<mediakit::MultiMediaSourceMuxer> (this=0x7f2410e6a0, __p=0x7f2410e6a0) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/ext/new_allocator.h:140
#8  0x000000000070ef90 in std::allocator_traits<std::allocator<mediakit::MultiMediaSourceMuxer> >::destroy<mediakit::MultiMediaSourceMuxer> (__a=..., __p=0x7f2410e6a0) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/alloc_traits.h:487
#9  0x000000000070ea1c in std::_Sp_counted_ptr_inplace<mediakit::MultiMediaSourceMuxer, std::allocator<mediakit::MultiMediaSourceMuxer>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7f2410e690) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:535
#10 0x0000000000468b30 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f2410e690) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:154
#11 0x00000000004673dc in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f1670d238, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:684
#12 0x000000000066e6a8 in std::__shared_ptr<mediakit::MultiMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f1670d230, __in_chrg=<optimized out>) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1123
#13 0x000000000070b420 in std::__shared_ptr<mediakit::MultiMediaSourceMuxer, (__gnu_cxx::_Lock_policy)2>::reset (this=0x7f255e2d08) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/shared_ptr_base.h:1235
#14 0x000000000070486c in mediakit::PlayerProxy::<lambda(const toolkit::SockException&)>::operator()(const toolkit::SockException &) const (__closure=0x7f257fdec0, err=...) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Player/PlayerProxy.cpp:91
#15 0x0000000000706efc in std::_Function_handler<void(const toolkit::SockException&), mediakit::PlayerProxy::play(const string&)::<lambda(const toolkit::SockException&)> >::_M_invoke(const std::_Any_data &, const toolkit::SockException &) (__functor=..., __args#0=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:316
#16 0x0000000000605b64 in std::function<void (toolkit::SockException const&)>::operator()(toolkit::SockException const&) const (this=0x7f257fe7f0, __args#0=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#17 0x00000000007eb9cc in mediakit::PlayerImp<mediakit::RtspPlayer, mediakit::PlayerBase>::onShutdown (this=0x7f257fe100, ex=...) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Player/PlayerBase.h:212
#18 0x00000000007e1d40 in mediakit::RtspPlayer::onPlayResult_l (this=0x7f257fe100, ex=..., handshake_done=true) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Rtsp/RtspPlayer.cpp:698
#19 0x00000000007e1adc in mediakit::RtspPlayer::<lambda()>::operator()(void) const (__closure=0x7f2410b8c0) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/src/Rtsp/RtspPlayer.cpp:716
#20 0x00000000007e4234 in std::_Function_handler<bool(), mediakit::RtspPlayer::onPlayResult_l(const toolkit::SockException&, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:302
#21 0x00000000009bf2ac in std::function<bool ()>::operator()() const (this=0x7f25638500) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#22 0x00000000009f5470 in toolkit::Timer::<lambda()>::operator()(void) const (__closure=0x7f25638500) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/Timer.cpp:22
#23 0x00000000009f58f4 in std::_Function_handler<long unsigned int(), toolkit::Timer::Timer(float, const std::function<bool()>&, const Ptr&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:302
#24 0x00000000009ec98c in std::function<unsigned long ()>::operator()() const (this=0x7f2410da60) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/std_function.h:706
#25 0x00000000009eafb4 in toolkit::TaskCancelableImp<unsigned long ()>::operator()() const (this=0x7f2410b8f0) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Thread/TaskExecutor.h:111
#26 0x00000000009e72e0 in toolkit::EventPoller::flushDelayTask (this=0x7f255f1300, now_time=23071) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:394
#27 0x00000000009e7578 in toolkit::EventPoller::getMinDelay (this=0x7f255f1300) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:428
#28 0x00000000009e6eb8 in toolkit::EventPoller::runLoop (this=0x7f255f1300, blocked=true, ref_self=true) at /home/momooy/work/01_QT_PRJ/da13/opensource/ZLMediaKit-debug/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:291
#29 0x00000000009ec5d4 in std::__invoke_impl<void, void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__f=@0x7f255f0418: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x9e6ddc <toolkit::EventPoller::runLoop(bool, bool)>, __t=@0x7f255f0410: 0x7f255f1300, __args#0=@0x7f255f0409: true, __args#1=@0x7f255f0408: true) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/invoke.h:73
#30 0x00000000009ead24 in std::__invoke<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__fn=@0x7f255f0418: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x9e6ddc <toolkit::EventPoller::runLoop(bool, bool)>, __args#0=@0x7f255f0410: 0x7f255f1300, __args#1=@0x7f255f0409: true, __args#2=@0x7f255f0408: true) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/bits/invoke.h:95
#31 0x00000000009f4e2c in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::_M_invoke<0ul, 1ul, 2ul, 3ul> (this=0x7f255f0408) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:234
#32 0x00000000009f4c4c in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::operator() (this=0x7f255f0408) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:243
#33 0x00000000009f4a40 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> > >::_M_run (this=0x7f255f0400) at /opt/hisi-linux/x86-arm/aarch64-himix200-linux/aarch64-linux-gnu/include/c++/7.3.0/thread:186
#34 0x0000007fbec287ec in ?? () from target:/lib64/libstdc++.so.6
#35 0x0000007fbed128f0 in ?? () from target:/lib64/libpthread.so.0
#36 0x0000007fbe9ec39c in ?? () from target:/lib64/libc.so.6
</pre>
</details>

**Comment by momooy** [comment]
折腾了很久，终于找出来是自己应用有bug
