### ISSUE TITLE
[BUG] 大量RTSP并发推流，偶发崩溃

### ISSUE THREAD

**Issue by Huachao** [ZLMediaKit/ZLMediaKit#3008]
### 现象描述

计划同时进行1000路设备并发RTSP推流，但是在400路左右的时候，ZLM突然出现崩溃。夏楚大佬，由于线上环境不方便升级ZLToolKit，所以也不确定最新的ZLToolKit是否有此问题。

### 相关日志或截图
Coredump 堆栈信息

<details>
<summary>展开查看详细日志</summary>
<pre>
#0  0x0000000000d19a22 in __gnu_cxx::__atomic_add (__mem=0x31203a2022657085, __val=1) at /usr/include/c++/4.8.2/ext/atomicity.h:53
#1  0x0000000000d19ae0 in __gnu_cxx::__atomic_add_dispatch (__mem=0x31203a2022657085, __val=1) at /usr/include/c++/4.8.2/ext/atomicity.h:96
#2  0x0000000000d2be1f in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_weak_add_ref (this=0x31203a2022657079) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:168
#3  0x0000000000d2a6eb in std::__weak_count<(__gnu_cxx::_Lock_policy)2>::__weak_count (this=0x7fc4f6e8e238, __r=...) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:629
#4  0x0000000000e322ab in std::__weak_ptr<toolkit::TcpClient, (__gnu_cxx::_Lock_policy)2>::__weak_ptr (this=0x7fc4f6e8e230) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:1195
#5  0x0000000000e322f7 in std::weak_ptr<toolkit::TcpClient>::weak_ptr (this=0x7fc4f6e8e230) at /usr/include/c++/4.8.2/bits/shared_ptr.h:461
#6  0x0000000000e3140d in toolkit::TcpClient::__lambda14::<lambda>(const toolkit::TcpClient::__lambda14 &) (this=0x7fc4f6e8e230) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Network/TcpClient.cpp:80
#7  0x0000000000e31449 in std::_Function_base::_Base_manager<toolkit::TcpClient::startConnect(const string&, uint16_t, float, uint16_t)::__lambda14>::_M_clone(std::_Any_data &, const std::_Any_data &, std::false_type) (__dest=..., __source=...) at /usr/include/c++/4.8.2/functional:1910
#8  0x0000000000e30e2f in std::_Function_base::_Base_manager<toolkit::TcpClient::startConnect(const string&, uint16_t, float, uint16_t)::__lambda14>::_M_manager(std::_Any_data &, const std::_Any_data &, std::_Manager_operation) (__dest=..., __source=..., __op=std::__clone_functor) at /usr/include/c++/4.8.2/functional:1946
#9  0x0000000000d2a987 in std::function<void (toolkit::SockException const&)>::function(std::function<void (toolkit::SockException const&)> const&) (this=0x7fc4f7bf9bc8, __x=...)
    at /usr/include/c++/4.8.2/functional:2442
#10 0x0000000000e1b3fd in toolkit::Socket::__lambda15::<lambda>(const toolkit::Socket::__lambda15 &) (this=0x7fc4f7bf9bc8) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp:144
#11 0x0000000000e1b746 in toolkit::Socket::__lambda16::operator() (__closure=0x7fc4da3ee970, sock=143) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp:176
#12 0x0000000000e25926 in std::_Function_handler<void(int), toolkit::Socket::connect_l(const string&, uint16_t, const onErrCB&, float, const string&, uint16_t)::__lambda16>::_M_invoke(const std::_Any_data &, int) (__functor=..., __args#0=143) at /usr/include/c++/4.8.2/functional:2071
#13 0x0000000000e274c6 in std::function<void (int)>::operator()(int) const (this=0x7fc4da3ee6b8, __args#0=143) at /usr/include/c++/4.8.2/functional:2471
#14 0x0000000000e1ba9a in toolkit::Socket::__lambda19::__lambda20::operator() (__closure=0x7fc4e7a00220) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp:199
#15 0x0000000000e21e31 in std::_Function_handler<void(), toolkit::Socket::connect_l(const string&, uint16_t, const onErrCB&, float, const string&, uint16_t)::__lambda19::__lambda20>::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/4.8.2/functional:2071
#16 0x0000000000d297fe in std::function<void ()>::operator()() const (this=0x7fc4d98123e8) at /usr/include/c++/4.8.2/functional:2471
#17 0x0000000000e56452 in toolkit::TaskCancelableImp<void ()>::operator()() const (this=0x7fc4d972f798) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Thread/TaskExecutor.h:111
#18 0x0000000000e55c43 in toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}::operator()(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&) const (__closure=0x7fc4f7bfa2b0, task=warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<toolkit::TaskCancelableImp<void ()>, std::allocator<toolkit::TaskCancelableImp<void ()> >, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<toolkit::TaskCancelableImp<void ()>, std::allocator<toolkit::TaskCancelableImp<void ()> >, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr (count 1, weak 0) 0x7fc4d972f798) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:251
#19 0x0000000000e56cff in toolkit::List<std::shared_ptr<toolkit::TaskCancelableImp<void ()> > >::for_each<toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}>(toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}&&) (this=0x7fc4f7bfa260, 
    func=<unknown type in /opt/zlm/MediaServer, CU 0x508ebb, DIE 0x5400b0>) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Util/List.h:203
#20 0x0000000000e55eee in toolkit::EventPoller::onPipeEvent (this=0x7fc4fc1d4890) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:257
#21 0x0000000000e51ba8 in toolkit::EventPoller::__lambda9::operator() (__closure=0x7fc4fc184370, event=1) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:57
#22 0x0000000000e5456a in std::_Function_handler<void(int), toolkit::EventPoller::addEventPipe()::__lambda9>::_M_invoke(const std::_Any_data &, int) (__functor=..., __args#0=1)
    at /usr/include/c++/4.8.2/functional:2071
#23 0x0000000000e274c6 in std::function<void (int)>::operator()(int) const (this=0x7fc4fd72a0d8, __args#0=1) at /usr/include/c++/4.8.2/functional:2471
#24 0x0000000000e53597 in toolkit::EventPoller::runLoop (this=0x7fc4fc1d4890, blocked=true, ref_self=true) at /opt/ZLMediaKit/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:322
#25 0x0000000000e61336 in std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const (this=0x7fc4fd7c72d0, __object=0x7fc4fc1d4890)
    at /usr/include/c++/4.8.2/functional:601
#26 0x0000000000e6114d in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>) (
    this=0x7fc4fd7c72c0) at /usr/include/c++/4.8.2/functional:1732
#27 0x0000000000e60e8d in std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()() (this=0x7fc4fd7c72c0)
    at /usr/include/c++/4.8.2/functional:1720
#28 0x0000000000e60bd6 in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run() (this=0x7fc4fd7c72a8)
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
{
        "code" : 0,
        "data" : 
        [
                {
                        "api.apiDebug" : "1",
                        "api.defaultSnap" : "./www/logo.png",
                        "api.secret" : "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
                        "api.snapRoot" : "./www/snap/",
                        "cluster.origin_url" : "",
                        "cluster.retry_count" : "3",
                        "cluster.timeout_sec" : "15",
                        "ffmpeg.bin" : "/usr/local/bin/ffmpeg",
                        "ffmpeg.cmd" : "%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
                        "ffmpeg.log" : "./ffmpeg/ffmpeg.log",
                        "ffmpeg.restart_sec" : "0",
                        "ffmpeg.snap" : "%s -i %s -y -f mjpeg -t 0.001 %s",
                        "general.addMuteAudio" : "1",
                        "general.check_nvidia_dev" : "1",
                        "general.continue_push_ms" : "15000",
                        "general.enableVhost" : "0",
                        "general.enable_audio" : "1",
                        "general.enable_ffmpeg_log" : "0",
                        "general.flowThreshold" : "1024",
                        "general.fmp4_demand" : "1",
                        "general.hls_demand" : "1",
                        "general.maxStreamWaitMS" : "30000",
                        "general.mediaServerId" : "hnXNunA2ydTyJEUQ",
                        "general.mergeWriteMS" : "0",
                        "general.modifyStamp" : "0",
                        "general.publishToHls" : "1",
                        "general.publishToMP4" : "0",
                        "general.resetWhenRePlay" : "1",
                        "general.rtmp_demand" : "0",
                        "general.rtsp_demand" : "0",
                        "general.streamNoneReaderDelayMS" : "30000",
                        "general.ts_demand" : "1",
                        "general.unready_frame_cache" : "100",
                        "general.wait_add_track_ms" : "3000",
                        "general.wait_track_ready_ms" : "15000",
                        "hls.broadcastRecordTs" : "0",
                        "hls.deleteDelaySec" : "0",
                        "hls.fileBufSize" : "65536",
                        "hls.filePath" : "./www",
                        "hls.segDur" : "2",
                        "hls.segKeep" : "0",
                        "hls.segNum" : "3",
                        "hls.segRetain" : "5",
                        "hook.admin_params" : "secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc",
                        "hook.alive_interval" : "10.0",
                        "hook.enable" : "1",
                        "hook.on_flow_report" : "",
                        "hook.on_http_access" : "",
                        "hook.on_play" : "",
                        "hook.on_publish" : "http://iotx-private-vision-edge-svc:8080/api/zlm/callback/on_publish",
                        "hook.on_record_mp4" : "",
                        "hook.on_record_ts" : "",
                        "hook.on_rtp_server_timeout" : "",
                        "hook.on_rtsp_auth" : "",
                        "hook.on_rtsp_realm" : "",
                        "hook.on_send_rtp_stopped" : "",
                        "hook.on_server_keepalive" : "",
                        "hook.on_server_started" : "",
                        "hook.on_shell_login" : "",
                        "hook.on_stream_changed" : "http://iotx-private-vision-edge-svc:8080/api/zlm/callback/on_stream_changed",
                        "hook.on_stream_none_reader" : "http://iotx-private-vision-edge-svc:8080/api/zlm/callback/on_stream_none_reader",
                        "hook.on_stream_not_found" : "",
                        "hook.retry" : "1",
                        "hook.retry_delay" : "3.000000",
                        "hook.timeoutSec" : "20",
                        "http.allow_cross_domains" : "1",
                        "http.charSet" : "utf-8",
                        "http.dirMenu" : "1",
                        "http.forbidCacheSuffix" : "",
                        "http.forwarded_ip_header" : "",
                        "http.keepAliveSecond" : "30",
                        "http.maxReqSize" : "40960",
                        "http.notFound" : "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>\u60a8\u8bbf\u95ee\u7684\u8d44\u6e90\u4e0d\u5b58\u5728\uff01</h1></center><hr><center>ZLMediaKit(git hash:4866410/%aI,branch:feature/20230524_v2.0.0,build time:2023-10-07T10:37:58)</center></body></html>",
                        "http.port" : "80",
                        "http.rootPath" : "./www",
                        "http.sendBufSize" : "65536",
                        "http.sslport" : "443",
                        "http.virtualPath" : "",
                        "multicast.addrMax" : "239.255.255.255",
                        "multicast.addrMin" : "239.0.0.0",
                        "multicast.udpTTL" : "64",
                        "protocol.add_mute_audio" : "1",
                        "protocol.continue_push_ms" : "15000",
                        "protocol.enable_audio" : "0",
                        "protocol.enable_fmp4" : "1",
                        "protocol.enable_hls" : "1",
                        "protocol.enable_mp4" : "0",
                        "protocol.enable_rtmp" : "1",
                        "protocol.enable_rtsp" : "1",
                        "protocol.enable_ts" : "1",
                        "protocol.fmp4_demand" : "0",
                        "protocol.hls_demand" : "0",
                        "protocol.hls_save_path" : "./www",
                        "protocol.modify_stamp" : "2",
                        "protocol.mp4_as_player" : "0",
                        "protocol.mp4_max_second" : "3600",
                        "protocol.mp4_save_path" : "./www",
                        "protocol.rtmp_demand" : "0",
                        "protocol.rtsp_demand" : "0",
                        "protocol.ts_demand" : "0",
                        "record.appName" : "record",
                        "record.fastStart" : "0",
                        "record.fileBufSize" : "65536",
                        "record.filePath" : "./www",
                        "record.fileRepeat" : "0",
                        "record.fileSecond" : "3600",
                        "record.sampleMS" : "500",
                        "rtc.externIP" : "",
                        "rtc.port" : "8000",
                        "rtc.preferredCodecA" : "PCMU,PCMA,opus,mpeg4-generic",
                        "rtc.preferredCodecV" : "H264,H265,AV1X,VP9,VP8",
                        "rtc.rembBitRate" : "0",
                        "rtc.timeoutSec" : "15",
                        "rtmp.handshakeSecond" : "15",
                        "rtmp.keepAliveSecond" : "15",
                        "rtmp.modifyStamp" : "0",
                        "rtmp.port" : "1935",
                        "rtmp.sslport" : "0",
                        "rtp.audioMtuSize" : "600",
                        "rtp.lowLatency" : "0",
                        "rtp.rtpMaxSize" : "10",
                        "rtp.videoMtuSize" : "1400",
                        "rtp_proxy.dumpDir" : "",
                        "rtp_proxy.gop_cache" : "1",
                        "rtp_proxy.h264_pt" : "98",
                        "rtp_proxy.h265_pt" : "99",
                        "rtp_proxy.opus_pt" : "100",
                        "rtp_proxy.port" : "10000",
                        "rtp_proxy.port_range" : "30000-35000",
                        "rtp_proxy.ps_pt" : "96",
                        "rtp_proxy.timeoutSec" : "15",
                        "rtsp.authBasic" : "0",
                        "rtsp.directProxy" : "1",
                        "rtsp.handshakeSecond" : "15",
                        "rtsp.keepAliveSecond" : "15",
                        "rtsp.lowLatency" : "0",
                        "rtsp.port" : "554",
                        "rtsp.rtpTransportType" : "-1",
                        "rtsp.sslport" : "0",
                        "shell.maxReqSize" : "1024",
                        "shell.port" : "0",
                        "srt.latencyMul" : "4",
                        "srt.pktBufSize" : "8192",
                        "srt.port" : "9000",
                        "srt.timeoutSec" : "5"
                }
        ]
}
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: ZLMediaKit/ZLToolKit@79db405ba43c29453c60c3e054d863ce6bd1ef29
* **操作系统及版本**: CentOS 7
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个问题 可能是之前zlm修复的一个底层网络bug 055fe2cb92dc0c1357dde8aeba6eaf7995c444aa

你要不更新代码试试？我回退代码到你的版本 查看stack，定位代码在这：
<img width="967" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/b806f2e6-4284-43f8-b975-da7d374af856">

不过看不出什么头绪。

**Comment by Huachao** [comment]
@xia-chu 谢谢夏楚大佬，那我试下。我还想问下，可以只升级ZLToolKit吗，还是需要ZLMediaKIt也一起升级？

**Comment by xia-chu** [comment]
> @xia-chu 谢谢夏楚大佬，那我试下。我还想问下，可以只升级ZLToolKit吗，还是需要ZLMediaKIt也一起升级？

只升级ZLToolKit就行 不过建议你一起升级
