### ISSUE TITLE
[BUG] chrome 123.0.6312.59 64 位 版本使用webrtc播放视频失败

### ISSUE THREAD

**Issue by chenfei2341** [ZLMediaKit/ZLMediaKit#3400]
### 现象描述
在chrome 123.0.6312.59（正式版本） （64 位） 中使用webrtc播放视频失败，提示错误

```
debug.js:22 [RTCPusherPlayer] DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected
    at RTCPeerConnection.setRemoteDescription (http://172.24.39.38:8080/webrtc/ZLMRTCClient.js:5183:40)
    at http://172.24.39.38:8080/webrtc/ZLMRTCClient.js:7896:20
```
在122版本可以正常播放

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
```
[RTCPusherPlayer] Remote ICE candidate: 
 candidate:4146156255 1 udp 2113937151 2b546a46-4916-4afb-8060-effcd85a662e.local 56442 typ host generation 0 ufrag 3pzS network-cost 999
debug.js:17 [RTCPusherPlayer] Remote ICE candidate: 
 candidate:4146156255 1 udp 2113937151 2b546a46-4916-4afb-8060-effcd85a662e.local 56444 typ host generation 0 ufrag 3pzS network-cost 999
debug.js:17 [RTCPusherPlayer] answer: v=0
o=- 5282881727892566462 2 IN IP4 172.24.39.38
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
a=ice-lite
m=video 8000 UDP/TLS/RTP/SAVPF 102 103
c=IN IP4 172.24.39.38
a=rtcp:8000 IN IP4 172.24.39.38
a=ice-ufrag:zlm_86
a=ice-pwd:f9DXPluoxTV1l7bm6Gbse0dY
a=ice-options:trickle
a=fingerprint:sha-256 13:06:47:6A:57:D5:FD:71:E4:47:E4:3E:F3:31:1A:ED:D0:64:FA:64:74:72:F3:54:AA:10:D3:6B:08:27:03:9A
a=setup:passive
a=mid:0
a=ice-lite
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=rtcp-mux
a=rtpmap:102 H264/90000
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtcp-fb:102 transport-cc
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 cname:zlmediakit-rtp
a=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 mslabel:zlmediakit-mslabel
a=ssrc:1 label:zlmediakit-label
a=ssrc:3 cname:zlmediakit-rtp
a=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:3 mslabel:zlmediakit-mslabel
a=ssrc:3 label:zlmediakit-label
a=ssrc-group:FID 1 3
a=candidate:udpcandidate 1 udp 110 172.24.39.38 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 172.24.39.38 8000 typ host tcptype passive
m=audio 8000 UDP/TLS/RTP/SAVPF 0
c=IN IP4 172.24.39.38
a=rtcp:8000 IN IP4 172.24.39.38
a=ice-ufrag:zlm_86
a=ice-pwd:f9DXPluoxTV1l7bm6Gbse0dY
a=ice-options:trickle
a=fingerprint:sha-256 13:06:47:6A:57:D5:FD:71:E4:47:E4:3E:F3:31:1A:ED:D0:64:FA:64:74:72:F3:54:AA:10:D3:6B:08:27:03:9A
a=setup:passive
a=mid:1
a=ice-lite
a=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=inactive
a=rtcp-mux
a=rtpmap:0 PCMU/8000/1
a=msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:2 cname:zlmediakit-rtp
a=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:2 mslabel:zlmediakit-mslabel
a=ssrc:2 label:zlmediakit-label
a=candidate:udpcandidate 1 udp 110 172.24.39.38 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 172.24.39.38 8000 typ host tcptype passive

```
```
debug.js:22 [RTCPusherPlayer] DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected
    at RTCPeerConnection.setRemoteDescription (http://172.24.39.38:8080/webrtc/ZLMRTCClient.js:5183:40)
    at http://172.24.39.38:8080/webrtc/ZLMRTCClient.js:7896:20
```
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
使用最新版本，这个已经修复了 https://github.com/ZLMediaKit/ZLMediaKit/issues/3396
