### ISSUE TITLE
使用WebRTC无法播放

### ISSUE THREAD

**Issue by wusiwee** [ZLMediaKit/ZLMediaKit#3512]
**咨询的功能模块**
- webrtc播放

**咨询的具体内容和问题**
- 部署系统：ubuntu
- 访问环境：内网
在使用webrtc在线播放，浏览器conslog输出：
```javascript
debug.js:17 [RTCPusherPlayer] answer: v=0
o=- 2402547014569582206 2 IN IP4 192.168.1.129
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS
a=ice-lite
m=audio 8000 UDP/TLS/RTP/SAVPF 111
c=IN IP4 192.168.1.129
a=rtcp:8000 IN IP4 192.168.1.129
a=ice-ufrag:zlm11
a=ice-pwd:fu6F2c5QlTytmbrIHtvZfkzY
a=ice-options:trickle
a=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3
a=setup:passive
a=mid:0
a=ice-lite
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=inactive
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:2 cname:zlmediakit-rtp
a=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:2 mslabel:zlmediakit-mslabel
a=ssrc:2 label:zlmediakit-label
a=candidate:udpcandidate 1 udp 110 192.168.1.129 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 192.168.1.129 8000 typ host tcptype passive
m=video 8000 UDP/TLS/RTP/SAVPF 102 103
c=IN IP4 192.168.1.129
a=rtcp:8000 IN IP4 192.168.1.129
a=ice-ufrag:zlm11
a=ice-pwd:fu6F2c5QlTytmbrIHtvZfkzY
a=ice-options:trickle
a=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3
a=setup:passive
a=mid:1
a=ice-lite
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=rtcp-mux
a=rtpmap:102 H264/90000
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtcp-fb:102 transport-cc
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 cname:zlmediakit-rtp
a=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:1 mslabel:zlmediakit-mslabel
a=ssrc:1 label:zlmediakit-label
a=ssrc:3 cname:zlmediakit-rtp
a=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label
a=ssrc:3 mslabel:zlmediakit-mslabel
a=ssrc:3 label:zlmediakit-label
a=ssrc-group:FID 1 3
a=candidate:udpcandidate 1 udp 110 192.168.1.129 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 192.168.1.129 8000 typ host tcptype passive

debug.js:22 [RTCPusherPlayer] DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected
    at e.RTCPeerConnection.setRemoteDescription (https://192.168.1.129:12443/static/js/liveplayer-lib.min.js:1:756159)
    at RTCPeerConnection.setRemoteDescription (https://192.168.1.129:12443/static/js/ZLMRTCClient.js:5187:40)
    at https://192.168.1.129:12443/static/js/ZLMRTCClient.js:7376:20
error @ debug.js:22
(anonymous) @ endpoint.js:117
Promise.catch (async)
(anonymous) @ endpoint.js:114
Promise.then (async)
(anonymous) @ endpoint.js:102
Promise.then (async)
(anonymous) @ endpoint.js:93
Promise.then (async)
receive @ endpoint.js:91
RTCEndpoint @ endpoint.js:69
play @ rtcPlayer.vue:38
(anonymous) @ rtcPlayer.vue:26
(anonymous) @ vue.esm.js:1989
Kt @ vue.esm.js:1915
Promise.then (async)
qt @ vue.esm.js:1942
ne @ vue.esm.js:1999
t.$nextTick @ vue.esm.js:3530
currentName @ element-ui.common.js:24204
mn.run @ vue.esm.js:4577
fn @ vue.esm.js:4319
(anonymous) @ vue.esm.js:1989
Kt @ vue.esm.js:1915
Promise.then (async)
qt @ vue.esm.js:1942
ne @ vue.esm.js:1999
(anonymous) @ vue.esm.js:4411
mn.update @ vue.esm.js:4553
dt.notify @ vue.esm.js:739
set @ vue.esm.js:1064
gn.set @ vue.esm.js:4640
n @ element-ui.common.js:24257
setCurrentName @ element-ui.common.js:24274
handleTabClick @ element-ui.common.js:24240
click @ element-ui.common.js:24074
Wt @ vue.esm.js:1863
n @ vue.esm.js:2188
o._wrapper @ vue.esm.js:7565
Show 24 more frames
Show less
2debug.js:17 Remote ICE candidate: 
 candidate:446400802 1 tcp 1518280447 192.168.2.160 9 typ host tcptype active generation 0 ufrag GVE0 network-id 1
```

`ZLMedia服务器日志：`
```javascript
024-05-06 14:10:53.030 W [MediaServer] [17-event poller 4] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
2024-05-06 14:10:55.231 D [MediaServer] [17-event poller 1] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/getRtpInfo
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 91
Content-Type : application/x-www-form-urlencoded
Host : 192.168.1.129:10080
User-Agent : okhttp/4.10.0
# content:
secret=cNaoX20Y289QgWIuFwM7KqYMVq156Wde&stream_id=34020000001320000008_34020000001320000008
# response:
{
    "code" : 0,
    "exist" : false
}


2024-05-06 14:10:55.234 I [MediaServer] [17-event poller 1] Rtsp.cpp:413 getPortPair | got port from pool:30048-30049
2024-05-06 14:10:55.234 D [MediaServer] [17-event poller 1] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/openRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 123
Content-Type : application/x-www-form-urlencoded
Host : 192.168.1.129:10080
User-Agent : okhttp/4.10.0
# content:
secret=cNaoX20Y289QgWIuFwM7KqYMVq156Wde&re_use_port=0&stream_id=34020000001320000008_34020000001320000008&port=0&tcp_mode=0
# response:
{
    "code" : 0,
    "port" : 30048
}


2024-05-06 14:10:55.448 I [MediaServer] [17-event poller 1] GB28181Process.cpp:178 onRtpDecode | 34020000001320000008_34020000001320000008 judged to be PS
2024-05-06 14:10:55.448 I [MediaServer] [17-event poller 1] Decoder.cpp:240 onTrack | got track: H264
2024-05-06 14:10:55.448 I [MediaServer] [17-event poller 1] Decoder.cpp:240 onTrack | got track: PCMA
2024-05-06 14:10:55.448 I [MediaServer] [17-event poller 1] Decoder.cpp:159 onStream | add track finished
2024-05-06 14:10:55.463 W [MediaServer] [17-event poller 1] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
2024-05-06 14:10:55.474 D [MediaServer] [17-event poller 1] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 119
Content-Type : application/x-www-form-urlencoded
Host : 192.168.1.129:10080
User-Agent : okhttp/4.10.0
# content:
secret=cNaoX20Y289QgWIuFwM7KqYMVq156Wde&app=rtp&vhost=__defaultVhost__&stream=34020000001320000008_34020000001320000008
# response:
{
    "code" : 0
}


2024-05-06 14:10:55.486 I [MediaServer] [17-event poller 1] RtpProcess.cpp:264 operator() | 34020000001320000008_34020000001320000008(192.168.1.9:4042) 允许RTP推流
2024-05-06 14:10:55.557 D [MediaServer] [17-event poller 1] MediaSink.cpp:150 emitAllTrackReady | All track ready use 71ms
2024-05-06 14:10:55.560 I [MediaServer] [17-event poller 1] MediaSource.cpp:503 emitEvent | 媒体注册:fmp4://__defaultVhost__/rtp/34020000001320000008_34020000001320000008
2024-05-06 14:10:55.560 I [MediaServer] [17-event poller 1] MultiMediaSourceMuxer.cpp:450 onAllTrackReady | stream: rtp://__defaultVhost__/rtp/34020000001320000008_34020000001320000008 , codec info: PCMA[8000/1/16] H264[1920/1080/25] 
2024-05-06 14:10:55.562 I [MediaServer] [17-event poller 1] MediaSource.cpp:503 emitEvent | 媒体注册:rtsp://__defaultVhost__/rtp/34020000001320000008_34020000001320000008
2024-05-06 14:10:55.564 I [MediaServer] [17-event poller 1] MediaSource.cpp:503 emitEvent | 媒体注册:rtmp://__defaultVhost__/rtp/34020000001320000008_34020000001320000008
2024-05-06 14:10:55.565 I [MediaServer] [17-event poller 1] MediaSource.cpp:503 emitEvent | 媒体注册:ts://__defaultVhost__/rtp/34020000001320000008_34020000001320000008
2024-05-06 14:10:55.596 W [MediaServer] [17-event poller 1] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
2024-05-06 14:10:55.596 W [MediaServer] [17-event poller 1] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
    Last message repeated 3 times
2024-05-06 14:10:55.628 I [MediaServer] [17-work poller 5] Process.cpp:178 run | start child process 3906, log file:/opt/ZLMediaKit/release/linux/Debug/ffmpeg/ffmpeg.log.3906
2024-05-06 14:10:55.693 W [MediaServer] [17-event poller 2] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
2024-05-06 14:10:55.698 I [MediaServer] [17-event poller 2] WebRtcTransport.cpp:435 WebRtcTransportImp | zlm8
2024-05-06 14:10:55.701 D [MediaServer] [17-event poller 2] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/webrtc?app=rtp&stream=34020000001320000008_34020000001320000008&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br, zstd
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Content-Length : 6475
Content-Type : text/plain;charset=UTF-8
Host : 192.168.1.129:10443
Origin : https://192.168.1.129:12443
Referer : https://192.168.1.129:12443/
sec-ch-ua : "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-site
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
# content:
v=0
o=- 1805752412281781901 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:7ynT
a=ice-pwd:IMHnX4D5P3A0isA+NelecB95
a=ice-options:trickle
a=fingerprint:sha-256 CA:D8:92:1D:AE:A9:86:F8:36:94:83:89:70:21:BD:7D:F8:54:F3:0E:2E:24:D1:71:FE:93:49:21:12:8C:AC:B9
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 103 104 105 106 107 108 109 127 125 39 40 41 42 43 44 45 46 47 48 112 113 114 115 116 117 118 49
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:7ynT
a=ice-pwd:IMHnX4D5P3A0isA+NelecB95
a=ice-options:trickle
a=fingerprint:sha-256 CA:D8:92:1D:AE:A9:86:F8:36:94:83:89:70:21:BD:7D:F8:54:F3:0E:2E:24:D1:71:FE:93:49:21:12:8C:AC:B9
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp
# response:
{
    "code" : 0,
    "id" : "zlm8",
    "sdp" : "v=0\r\no=- 1805752412281781901 2 IN IP4 192.168.1.129\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\na=ice-lite\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 8\r\nc=IN IP4 192.168.1.129\r\na=rtcp:8000 IN IP4 192.168.1.129\r\na=ice-ufrag:zlm8\r\na=ice-pwd:wSjc37jaRkGBuE9OJylna2ae\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:8 PCMA/8000/1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\na=candidate:udpcandidate 1 udp 110 192.168.1.129 8000 typ host\r\na=candidate:tcpcandidate 1 tcp 105 192.168.1.129 8000 typ host tcptype passive\r\nm=video 8000 UDP/TLS/RTP/SAVPF 102 103\r\nc=IN IP4 192.168.1.129\r\na=rtcp:8000 IN IP4 192.168.1.129\r\na=ice-ufrag:zlm8\r\na=ice-pwd:wSjc37jaRkGBuE9OJylna2ae\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=rtcp-fb:102 transport-cc\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:103 rtx/90000\r\na=fmtp:103 apt=102\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 cname:zlmediakit-rtp\r\na=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 mslabel:zlmediakit-mslabel\r\na=ssrc:1 label:zlmediakit-label\r\na=ssrc:3 cname:zlmediakit-rtp\r\na=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:3 mslabel:zlmediakit-mslabel\r\na=ssrc:3 label:zlmediakit-label\r\na=ssrc-group:FID 1 3\r\na=candidate:udpcandidate 1 udp 110 192.168.1.129 8000 typ host\r\na=candidate:tcpcandidate 1 tcp 105 192.168.1.129 8000 typ host tcptype passive\r\n",
    "type" : "answer"
}


2024-05-06 14:10:55.715 W [MediaServer] [17-event poller 3] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
2024-05-06 14:10:55.721 I [MediaServer] [17-event poller 3] RtspSession.cpp:819 handleReq_Play | 1255-90(127.0.0.1:45696) rtsp seekTo(ms):0
2024-05-06 14:10:55.743 W [MediaServer] [17-event poller 1] WebRtcSession.cpp:106 onError | 1251-59(192.168.1.12:43484) 1(end of file)
2024-05-06 14:10:56.781 W [MediaServer] [17-event poller 3] RtspSession.cpp:64 onError | 1255-90(127.0.0.1:45696) RTSP播放器(__defaultVhost__/rtp/34020000001320000008_34020000001320000008)断开:connection reset by peer,耗时(s):1
2024-05-06 14:10:56.793 I [MediaServer] [17-work poller 5] Process.cpp:230 s_wait | process terminated, pid=3906, exit code=0
2024-05-06 14:10:56.793 D [MediaServer] [17-work poller 5] WebApi.cpp:258 http api debug | 
# request:
GET /index/api/getSnap?secret=cNaoX20Y289QgWIuFwM7KqYMVq156Wde&expire_sec=1&url=rtsp%3A%2F%2F127.0.0.1%3A554%2Frtp%2F34020000001320000008_34020000001320000008&timeout_sec=15
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Host : 192.168.1.129:10080
User-Agent : okhttp/4.10.0
# content:

# response size:102850

2024-05-06 14:10:56.793 W [MediaServer] [17-work poller 5] Process.cpp:288 s_kill | kill process 3906 failed:no such process

```
页面提示存在重复的a=msid 我仔细看了一下，确实存在两个相同的`a=msid:zlmediakit-mslabel zlmediakit-label` 
正确的播放应该是两个：`a=msid:zlmediakit-mslabel zlmediakit-label-0`和`a=msid:zlmediakit-mslabel zlmediakit-label-1`
我研究了两天，看了文档和iss，都找不出具体的原因，所以过来咨询一下

**Comment by xia-chu** [comment]
更新下zlm吧

**Comment by itweeSIWEI** [comment]
OK,我重新下载最新的编译一下
